### ISSUE TITLE
sigma as single value

### ISSUE THREAD

**Issue by GwladysLambert** [allanhicks/Ensemble#2]
suggest to consider changing _sigma_ to _as.matrix(sigma)_ line 86 in R / Utilities.R as the function _isSymmetric_ fails in _rmvnorm_ when using a single year and single param in _combineEnsemble.fn_ (i.e. single sigma value)

**Comment by allanhicks** [comment]
Works for single year. Thanks to @GwladysLambert for suggesting the fix
